# Question 1: Basic Quicksort
## Write a Python function to implement the basic Quicksort algorithm.
### •Include partitioning (pivot to be always in the middle of array) and recursive calls.
### • Define new left, middle, and right arrays!
### • Test your function using [5, 2, 8, 6, 0, 7, 1, 4, 9, 3]

In [12]:
def basic_quiksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr)//2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return basic_quiksort(left) + middle + basic_quiksort(right)

arr = [5, 2, 8, 6, 0, 7, 1, 4, 9, 3]
basic_quiksort(arr)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#  Question 2: Partitioning
## Implement the partitioning operation for the Quicksort algorithm.
### • Write a function that takes an array, a starting index, and an ending index, and rearranges the array elements around the pivot.
### • Test your partitioning function using [5, 2, 8, 6, 0, 7, 1, 4, 9, 3]

In [28]:
def partition(arr, p, r):
    x = arr[r]
    i = p - 1
    for j in range(p, r):
        if arr[j] <= x:
            i = i + 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i+1], arr[r] = arr[r], arr[i+1]
    return i+1

arr = [5, 2, 8, 6, 0, 7, 1, 4, 9, 3]
index = partition(arr, 0, len(arr)-1)
print(index)

3


# Question 3: Quicksort with Partitioning
## Implement the Quicksort algorithm using the partition function of question 2.
### • Test your Quicksort function using [5, 2, 8, 6, 0, 7, 1, 4, 9, 3]

In [29]:
def QUICKSORT(arr, p, r):
    if p < r:
        q = partition(arr, p, r)
        QUICKSORT(arr, p, q-1)
        QUICKSORT(arr, q+1, r)

arr = [5, 2, 8, 6, 0, 7, 1, 4, 9, 3]
QUICKSORT(arr, 0, len(arr) - 1)
print(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


# Question 4: Randomized Quicksort
### • Implement the randomized version of Quicksort using randomized partitioning technique.
### • Compare the performance of the randomized quicksort with original implementation of quicksort that select last element as pivot.
### • Test this comparison on various random arrays.

In [33]:
import numpy as np

def randomized_partition(arr, p, r):
    i = np.random.randint(p, r, size=1)
    arr[r], arr[i] = arr[i], arr[r]
    return partition(arr, p, r)

for i in [5, 10, 15, 20]:
    arr = np.random.randint(np.random.randint(2, 100), size=i)
    print(arr)
    ind = partition(arr, 0, len(arr)-1)
    rndind = randomized_partition(arr, 0, len(arr)-1)
    print("original : {}, random : {}".format(ind, rndind))


[24 39  5 27 11]
original : 1, random : 1
[5 4 4 1 6 8 3 2 0 8]
original : 9, random : 5
[63 70 19 22 38 22 42 51 68 54 13 43 69 38 67]
original : 11, random : 13
[18  1 10 14 18  1  7  3  7  1  5  1 18  5  5  8  4  2 11 11]
original : 15, random : 5


/var/folders/yd/tz7q7s1d7mq6bfn52dc7kxd40000gn/T/ipykernel_3924/4263614378.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  arr[r], arr[i] = arr[i], arr[r]


# Question 5: Descending Order of Randomized Quicksort
### • Implement randomized version of Quicksort to sort values in an array in descending order.
### • Test your implementation using [5, 2, 8, 6, 0, 7, 1, 4, 9, 3]

In [51]:
def partition(arr, p, r):
    x = arr[r]
    i = p - 1
    for j in range(p, r):
        if arr[j] >= x:
            i = i + 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i+1], arr[r] = arr[r], arr[i+1]
    return i+1

def randomized_partition(arr, p, r):
    i = np.random.randint(p, r)
    arr[r], arr[i] = arr[i], arr[r]
    return partition(arr, p, r)

def Randomized_Quicksort(arr, p, r):
    if p < r:
        q = randomized_partition(arr, p, r)
        Randomized_Quicksort(arr, p, q-1)
        Randomized_Quicksort(arr, q+1, r)

arr = [5, 2, 8, 6, 0, 7, 1, 4, 9, 3]
Randomized_Quicksort(arr, 0, len(arr) - 1)
print(arr)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
